export const SEARCH_TERM_STORE = 'SEARCH_TERM_STORE';
export const RESTRO_LOAD_FAILURE = 'RESTRO_LOAD_FAILURE';
export const RESTRO_LOAD_SUCCESS = 'RESTRO_LOAD_SUCCESS';
export const RESET_ERRORS = 'RESET_ERRORS';
export const CABS_LOAD_SUCCESS = 'CABS_LOAD_SUCCESS';
export const CABS_LOAD_FAILURE = 'CABS_LOAD_FAILURE';
export const GALLERY_LOAD_FAILURE = 'GALLERY_LOAD_FAILURE';
export const GALLERY_LOAD_SUCCESS = 'GALLERY_LOAD_SUCCESS';
export const GALLERY_RESET = 'GALLERY_RESET';
export const TAB_CHANGE = 'TAB_CHANGE';



